# Generated by Django 3.2.15 on 2022-10-24 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka', models.CharField(max_length=50)),
                ('modelAdi', models.CharField(max_length=50)),
                ('modelNo', models.CharField(max_length=50)),
                ('isletimSistemi', models.CharField(max_length=50)),
                ('islemciTipi', models.CharField(max_length=50)),
                ('islemciNesli', models.CharField(max_length=50)),
                ('ram', models.CharField(max_length=50)),
                ('diskBoyutu', models.CharField(max_length=50)),
                ('diskTuru', models.CharField(max_length=50)),
                ('ekranBoyu', models.CharField(max_length=50)),
                ('puani', models.CharField(max_length=5)),
                ('fiyat', models.DecimalField(decimal_places=2, max_digits=8)),
                ('prodLink', models.CharField(max_length=300)),
                ('imageLink', models.CharField(max_length=300)),
                ('prodTitle', models.CharField(max_length=300)),
                ('site', models.CharField(max_length=50)),
                ('puani2', models.CharField(default=None, max_length=5)),
                ('fiyat2', models.DecimalField(decimal_places=2, default=None, max_digits=8)),
                ('prodLink2', models.CharField(default=None, max_length=300)),
                ('site2', models.CharField(default=None, max_length=50)),
                ('puani3', models.CharField(default=None, max_length=5)),
                ('fiyat3', models.DecimalField(decimal_places=2, default=None, max_digits=8)),
                ('prodLink3', models.CharField(default=None, max_length=300)),
                ('site3', models.CharField(default=None, max_length=50)),
                ('puani4', models.CharField(default=None, max_length=5)),
                ('fiyat4', models.DecimalField(decimal_places=2, default=None, max_digits=8)),
                ('prodLink4', models.CharField(default=None, max_length=300)),
                ('site4', models.CharField(default=None, max_length=50)),
                ('puani5', models.CharField(default=None, max_length=5)),
                ('fiyat5', models.DecimalField(decimal_places=2, default=None, max_digits=8)),
                ('prodLink5', models.CharField(default=None, max_length=300)),
                ('site5', models.CharField(default=None, max_length=50)),
                ('puani6', models.CharField(default=None, max_length=5)),
                ('fiyat6', models.DecimalField(decimal_places=2, default=None, max_digits=8)),
                ('prodLink6', models.CharField(default=None, max_length=300)),
                ('site6', models.CharField(default=None, max_length=50)),
            ],
        ),
    ]
