# Generated by Django 3.2.15 on 2022-10-24 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_auto_20221024_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchproducts',
            name='prodId',
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
    ]
