# Generated by Django 3.2.15 on 2022-10-24 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MatchProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka', models.CharField(max_length=50)),
                ('modelAdi', models.CharField(max_length=50)),
                ('modelNo', models.CharField(max_length=50)),
                ('isletimSistemi', models.CharField(max_length=50)),
                ('islemciTipi', models.CharField(max_length=50)),
                ('islemciNesli', models.CharField(max_length=50)),
                ('ram', models.CharField(max_length=50)),
                ('diskBoyutu', models.CharField(max_length=50)),
                ('diskTuru', models.CharField(max_length=50)),
                ('ekranBoyu', models.CharField(max_length=50)),
                ('puani', models.CharField(max_length=5)),
                ('fiyat', models.DecimalField(decimal_places=2, max_digits=8)),
                ('prodLink', models.CharField(max_length=300)),
                ('imageLink', models.CharField(max_length=300)),
                ('prodTitle', models.CharField(max_length=300)),
                ('site', models.CharField(max_length=50)),
                ('puani2', models.CharField(blank=True, default=None, max_length=5, null=True)),
                ('fiyat2', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=8, null=True)),
                ('prodLink2', models.CharField(blank=True, default=None, max_length=300, null=True)),
                ('site2', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('puani3', models.CharField(blank=True, default=None, max_length=5, null=True)),
                ('fiyat3', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=8, null=True)),
                ('prodLink3', models.CharField(blank=True, default=None, max_length=300, null=True)),
                ('site3', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('puani4', models.CharField(blank=True, default=None, max_length=5, null=True)),
                ('fiyat4', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=8, null=True)),
                ('prodLink4', models.CharField(blank=True, default=None, max_length=300, null=True)),
                ('site4', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('puani5', models.CharField(blank=True, default=None, max_length=5, null=True)),
                ('fiyat5', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=8, null=True)),
                ('prodLink5', models.CharField(blank=True, default=None, max_length=300, null=True)),
                ('site5', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('puani6', models.CharField(blank=True, default=None, max_length=5, null=True)),
                ('fiyat6', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=8, null=True)),
                ('prodLink6', models.CharField(blank=True, default=None, max_length=300, null=True)),
                ('site6', models.CharField(blank=True, default=None, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka', models.CharField(max_length=200)),
                ('modelAdi', models.CharField(max_length=100)),
                ('modelNo', models.CharField(max_length=50)),
                ('isletimSistemi', models.CharField(max_length=100)),
                ('islemciTipi', models.CharField(max_length=100)),
                ('islemciNesli', models.CharField(max_length=100)),
                ('ram', models.CharField(max_length=100)),
                ('diskBoyutu', models.CharField(max_length=100)),
                ('diskTuru', models.CharField(max_length=100)),
                ('ekranBoyu', models.CharField(max_length=100)),
                ('puani', models.CharField(max_length=100)),
                ('fiyat', models.CharField(max_length=100)),
                ('site', models.CharField(max_length=30)),
                ('prodLink', models.CharField(max_length=200)),
                ('imageLink', models.CharField(max_length=200)),
                ('prodTitle', models.CharField(max_length=200)),
            ],
        ),
    ]
