# Generated by Django 3.2.15 on 2022-10-24 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchproducts',
            name='prodId',
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
    ]
